name: tusharsonigames
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.0.0+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_auth: ^3.1.0
  google_sign_in: ^5.1.0
  get: ^4.3.8
  dio: ^4.0.0
  google_fonts: ^2.1.0
  firebase_messaging: ^10.0.6
  cached_network_image: ^3.1.0
  firebase_database: ^7.2.1
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  url_launcher: ^6.0.10
  auto_size_text: ^3.0.0-nullsafety.0
  razorpay_flutter: ^1.3.0
  pie_chart: ^5.0.0
  dotted_border: ^2.0.0+1
  share: ^2.0.4
  device_info: ^2.0.2
  package_info: ^2.0.2
  lottie: ^1.1.0
  connectivity: ^3.0.6


dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  adaptive_icon_foreground: "images/logo_fore.png"
  adaptive_icon_background: "#00ffff"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - images/loading.json
    - images/maintainance.json
    - images/refrence.json
    - images/nointernet.json
    - images/playgame.json
    - images/updateApp.json
    - images/resultout.json
    - images/anotherlogin.json
    - images/error.json
    - images/gameclose.json
    - images/successful.json
    - images/party_cat.json
    - images/firecracker.json
    - images/facebook.json
    - images/whatsapp.json
    - images/telegram.json


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: MainIcon
      fonts:
        - asset: icons/MainIcon.ttf

    - family: GoogleIcon
      fonts:
        - asset: icons/GoogleIcon.ttf

    - family: PlayGameIcon
      fonts:
        - asset: icons/PlayGameIcon.ttf

    - family: WalletIcon
      fonts:
        - asset: icons/WalletIcon.ttf

    - family: Maintanence
      fonts:
        - asset: icons/Maintanence.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
