/// Flutter icons GoogleIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GoogleIcon
///      fonts:
///       - asset: fonts/GoogleIcon.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class GoogleIcon {
  GoogleIcon._();

  static const _kFontFam = 'GoogleIcon';
  static const dynamic _kFontPkg = null;

  static const IconData gplus = IconData(0xf05a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
